/*
 * MIT License
 *
 * Copyright (c) 2015-2022 Oleksii Khalikov
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/*
 * Client Portal Web API
 * Client Poral Web API
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package ua.com.gfalcon.ibkr.client.okhttp.api;

import org.junit.Ignore;
import org.junit.Test;

import ua.com.gfalcon.ibkr.model.Body;
import ua.com.gfalcon.ibkr.model.Performance;
import ua.com.gfalcon.ibkr.model.Summary;
import ua.com.gfalcon.ibkr.model.Transactions;

/**
 * API tests for PortfolioAnalystApi
 */
@Ignore
public class PortfolioAnalystApiTest {

    private final PortfolioAnalystApi api = new PortfolioAnalystApi();


    /**
     * Account Performance
     * <p>
     * Returns the performance (MTM) for the given accounts, if more than one account is passed, the result is
     * consolidated.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void paPerformancePostTest() throws Exception {
        Body body = null;
        Performance response = api.paPerformancePost(body);

        // TODO: test validations
    }

    /**
     * Account Balance&#39;s Summary
     * <p>
     * Returns a summary of all account balances for the given accounts, if more than one account is passed, the result
     * is consolidated.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void paSummaryPostTest() throws Exception {
        Body body = null;
        Summary response = api.paSummaryPost(body);

        // TODO: test validations
    }

    /**
     * Position&#39;s Transaction History
     * <p>
     * transaction history for a given number of conids and accounts. Types of transactions include dividend payments,
     * buy and sell transactions, transfers.
     *
     * @throws Exception if the Api call fails
     */
    @Test
    public void paTransactionsPostTest() throws Exception {
        Body body = null;
        Transactions response = api.paTransactionsPost(body);

        // TODO: test validations
    }

}
